export const processStepId=[
        
            [
            {
                process_id:1,
                attribute_id:1,
                process_step_id:1
             }
        ],
        
     [{
            process_id:2,
            attribute_id:2,
            process_step_id:2
         },
         {
            process_id:2,
            attribute_id:3,
            process_step_id:3
         },
         {
            process_id:2,
            attribute_id:4,
            process_step_id:4
         }, {
            process_id:2,
            attribute_id:5,
            process_step_id:5
         }
      ],
         [
            {
                process_id:3,
                attribute_id:2,
                process_step_id:6
             },
             {
                process_id:3,
                attribute_id:3,
                process_step_id:7
             },
             {
                process_id:3,
                attribute_id:4,
                process_step_id:8
             },
             {
               process_id:3,
               attribute_id:5,
               process_step_id:9
            }
        ],
        [
        {
            process_id:4,
            attribute_id:2,
            process_step_id:10
         },
         {
            process_id:4,
            attribute_id:3,
            process_step_id:11
         },
         {
            process_id:4,
            attribute_id:4,
            process_step_id:12
         },
         {
            process_id:4,
            attribute_id:5,
            process_step_id:13
         }
       ],
       [
        {
           process_id:5,
           attribute_id:2,
           process_step_id:14
        },
         {
           process_id:5,
           attribute_id:3,
           process_step_id:15
        },
        {
           process_id:5,
           attribute_id:4,
           process_step_id:16
        },
        {
         process_id:5,
         attribute_id:4,
         process_step_id:17
      }
        ],
        [
        {
            process_id:6,
            attribute_id:2,
            process_step_id:18
         },
         {
            process_id:6,
            attribute_id:3,
            process_step_id:19
         },
         {
            process_id:6,
            attribute_id:4,
            process_step_id:20
         },
         {
            process_id:6,
            attribute_id:4,
            process_step_id:21
         }
        ],
        [
        {
            process_id:7,
            attribute_id:2,
            process_step_id:22
         },
         {
            process_id:7,
            attribute_id:3,
            process_step_id:23
         },
         {
            process_id:7,
            attribute_id:4,
            process_step_id:24
         },
         {
            process_id:7,
            attribute_id:4,
            process_step_id:25
         }
       ],[
        {
            process_id:8,
            attribute_id:2,
            process_step_id:26
         },
         {
            process_id:8,
            attribute_id:3,
            process_step_id:27
         },
         {
            process_id:8,
            attribute_id:4,
            process_step_id:28
         },
         {
            process_id:8,
            attribute_id:4,
            process_step_id:29
         },
         {
            process_id:8,
            attribute_id:4,
            process_step_id:30
         }
       ],
        [
        {
            process_id:9,
            attribute_id:2,
            process_step_id:31
         },
         {
            process_id:9,
            attribute_id:3,
            process_step_id:32
         },
         {
            process_id:9,
            attribute_id:4,
            process_step_id:33
         },
         {
            process_id:9,
            attribute_id:5,
            process_step_id:34
         }
       ]
     
 

]